### ISSUE TITLE
Exception using Matlab for LSA

### ISSUE THREAD

**Issue by N2D2** [fozziethebeat/S-Space#26]
Hi,
if I put the -S MATLAB command, Java throws
IllegalArgumentException: dimensions must be positive
at edu.ucla.sspace.matrix.OnDiskMatrix.<init>(OnDiskMatrix.java:98)
    at edu.ucla.sspace.matrix.Matrices.create(Matrices.java:216)
    at edu.ucla.sspace.matrix.MatrixIO.readDenseTextMatrix(MatrixIO.java:924)

In Matrices.create(Matrices.java:216) I find the lines:

 case SPARSE_ON_DISK:
                //return new SparseOnDiskMatrix(rows, cols);
                // REMDINER: implement me
                return new OnDiskMatrix(rows, cols);

Is the MATLAB matrix format not implemented yet or is it a bug?

The output above the Exception suggests a general problem with reading the Matlab-Output:

Nov 09, 2012 11:21:52 AM edu.ucla.sspace.matrix.MatrixIO readDenseTextMatrix
FINE: reading in text matrix with 15262 rows and 0 cols
Nov 09, 2012 11:21:52 AM edu.ucla.sspace.matrix.MatrixIO readDenseTextMatrix
FINE: reading in text matrix with 100 rows and 0 cols

And Matlab gives the warning:

> > > > Warning: Imaginary part of complex variable 'U' not saved to ASCII file. 
> > > > Warning: Imaginary part of complex variable 'V' not saved to ASCII file. 
> > > > But the three Matlab output matrices seem normal.

I use Mac 10.7, Matlab 2012a and the SSpace 2.0-Code (but this happened with earlier code, too)

**Comment by jerrygaoLondon** [comment]
I've encountered the same problem (IllegalArgumentException: dimensions must be positive) when running dimension reduction by using SingularValueDecompositionMatlab or SingularValueDecompositionOctave in Windows 7.

I have matlab installed. The problem is exactly the same as the one described by @ganonp .
I can see "Every time I run the program, matlab opens up to a command window,". However, no data can be written into matlab-svds-VXXX.dat, matlab-svds-SXXX.dat and matlab-svds-UXXX.dat. 

When i run the script (as below) in matlab, it works well. I suspect that there is an issue to make matlab script run correctly by writing scripts to matlab output stream. I have tried the version 2.0.4 and 2.0.3 and none of them works. Any ideas?

=====
Z=load('C:\\Users\\jerry\\AppData\\Local\\Temp\\matlab-input3613993774554135994.dat','-ascii');
A = spconvert(Z);
clear Z;
[U, S, V] = svds(A, 3);
save C:\\Users\\jerry\\AppData\\Local\\Temp\\matlab-svds-U8365859529350808097.dat  U -ASCII
save C:\\Users\\jerry\\AppData\\Local\\Temp\\matlab-svds-S1129545791491312334.dat  S -ASCII
save C:\\Users\\jerry\\AppData\\Local\\Temp\\matlab-svds-V4284815455262646654.dat  V -ASCII
fprintf('Matlab Finished\\n');
